### ISSUE TITLE
Incorrect calculation?

### ISSUE THREAD

**Issue by xilopaint** [MuppetGate/Alfred-Workflows-DateCalculator#7]
![qthk2fq](https://cloud.githubusercontent.com/assets/11052366/17640155/012fe9f8-60d1-11e6-9354-4a153bee31e5.png)

input = dcalc 06/07/2016 +20d x weekends
date format = dd/mm/yyyy
 
The correct output should be 03/08/2016.

**Comment by MuppetGate** [comment]
Hi there. 

Just adding this up on a calendar, and it looks correct to me. Excluding weekends from the calculation will land you on the 26.07.2016. The weekends that you are excluding comes to six days. Adding those days back in will take you to the 01.08.2016, not 03.08.2016

**Comment by xilopaint** [comment]
What does the workflow consider a weekend? Is it not every Saturday and Sunday? If so I can see eight days: 09.07, 10.07, 16.07, 17.07, 23.07, 24.07, 30.07 and 31.07.

**Comment by MuppetGate** [comment]
Ah, I see where you got your figure from now! 

Right, okay. I think the calculation is not doing quite what you think it does. 

The idea was suggested by a lawyer. Think of it like this:

Okay, from today, I have 20 days to complete this project, so what date am I due to finish?

06.07.2016 + 20d = 26.07.2016

But wait a minute, I don't work weekends, so what day am I due to finish if I don't work weekends.

06.07.2016 + 20d x weekends

That means we have to add the weekends up until 26.07.2016, not 31.07.2016.

Which is why the final date is 01.08.2016

**Comment by xilopaint** [comment]
Well, I am a lawyer in Brazil and this is exactly the reason I need this feature. I venture to say you did not understand well the [other lawyer's request](http://www.alfredforum.com/topic/4542-yet-another-date-calculator/page-3#entry33988). We need a feature that can calculate deadlines in court days (or working days). It's basically a calculation that consider only working days in the manner I told you.

**Comment by MuppetGate** [comment]
Hell, yes you're right! Just had to look at the calendar. I haven't accounted for the weekend that I've skipped over!

**Comment by MuppetGate** [comment]
Right, this sounds like a job for a recursive function!

**Comment by MuppetGate** [comment]
Okay, I'm going to have to pull the exclude functionality.

I've run through a few scenarios and I've realised that it's very easy to come up with an exclusion list that would cause the workflow to never find a matching date. That's not good.

**Comment by xilopaint** [comment]
Oh, it's bad news for us lawyers. This functionality would be very useful for my daily workflow. 😕

Thanks anyway.
